### ISSUE TITLE
The access to the dataset

### ISSUE THREAD

**Issue by leihui6** [qdushl/Waterloo-Point-Cloud-Database#3]
Hi,

Thanks for your dataset, but how can I have the access to it?

**Comment by qdushl** [comment]
需要一个谷歌账号，发起申请，然后我同意就行了。







| |
Honglei Su
Ph.D. ; Assistant Professor
|
|
Qingdao University, Qingdao, China
***@***.***
|
---- Replied Message ----
| From | Leihui ***@***.***> |
| Date | 4/23/2024 22:05 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [qdushl/Waterloo-Point-Cloud-Database] The access to the dataset (Issue #3) |

Hi,

Thanks for your dataset, but how can I have the access to it?
